[package]
name = "slice"
version = "0.3.0"
authors = ["Sriharsha Mucheli <harshasrisri@gmail.com>"]
edition = "2021"
description = "An opinionated implementation of the 'cut' *nix utility to slice rows and columns of data."

[dependencies]
structopt = "0.3.9"
field_spec = { path = "field_spec" }
