[package]
name = "slice"
version = "0.2.0"
authors = ["Sriharsha Mucheli <harshasrisri@gmail.com>"]
edition = "2018"
description = "An opinionated implementation of the 'cut' *nix utility to slice rows and columns of data."

[dependencies]
structopt = "0.3.9"
